services:
  - type: web
    name: zelantrix-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SERVICE_ACCOUNT_JSON
        sync: false
